//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dateDBEntities : DbContext
    {
        public dateDBEntities()
            : base("name=dateDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friend> Friend { get; set; }
        public virtual DbSet<Info> Info { get; set; }
        public virtual DbSet<User> User { get; set; }
        public virtual DbSet<Wall> Wall { get; set; }
        public virtual DbSet<FriendRequest> FriendRequest { get; set; }
    }
}
