//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication7.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dateDB1 : DbContext
    {
        public dateDB1()
            : base("name=dateDB1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Friend> Friends { get; set; }
        public virtual DbSet<Info> Infoes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wall> Walls { get; set; }
        public virtual DbSet<FriendRequest> FriendRequests { get; set; }
    }
}
